import type { CalendarEvent, WorkHours } from "./types";

export const DAYS = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
export const DAYS_FULL = [
    "Sunday",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
];
export const MONTHS = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
];
export const MONTHS_SHORT = [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
];
export const HOUR_H = 64;

export const SAMPLE_EVENTS: CalendarEvent[] = [
    {
        id: "evt-001",
        title: "Product Strategy Sync",
        description: "Quarterly roadmap review with the design team.",
        start: "2026-02-18T10:00:00",
        end: "2026-02-18T11:30:00",
        allDay: false,
        category: "work",
        color: "#10b981",
        isBookable: true,
        createdBy: { id: "u-1", name: "Alex Rivera" },
    },
    {
        id: "hol-001",
        title: "Presidents' Day",
        description: "National Holiday",
        start: "2026-02-16T00:00:00",
        end: "2026-02-16T23:59:59",
        allDay: true,
        category: "holiday",
        color: "#ef4444",
        isBookable: false,
        createdBy: { id: "system", name: "Admin" },
    },
    {
        id: "evt-002",
        title: "Deep Work Session",
        description: "Focus time for deep technical work.",
        location: "Home Office",
        start: "2026-02-19T14:00:00",
        end: "2026-02-19T17:00:00",
        allDay: false,
        category: "personal",
        color: "#6366f1",
        isBookable: true,
        createdBy: { id: "u-1", name: "Alex Rivera" },
    },
    {
        id: "evt-003",
        title: "Team Standup",
        description: "Daily sync with engineering.",
        start: "2026-02-17T09:00:00",
        end: "2026-02-17T09:30:00",
        allDay: false,
        category: "work",
        color: "#10b981",
        isBookable: false,
        createdBy: { id: "u-2", name: "Jordan Lee" },
    },
    {
        id: "evt-004",
        title: "Deadline: Q1 Report",
        description: "Submit the quarterly report.",
        start: "2026-02-20T17:00:00",
        end: "2026-02-20T18:00:00",
        allDay: false,
        category: "urgent",
        color: "#f59e0b",
        isBookable: false,
        createdBy: { id: "u-1", name: "Alex Rivera" },
    },
    {
        id: "evt-005",
        title: "Design Review",
        start: "2026-02-18T14:00:00",
        end: "2026-02-18T15:30:00",
        allDay: false,
        category: "work",
        color: "#10b981",
        isBookable: true,
        createdBy: { id: "u-3", name: "Sam Chen" },
    },
    {
        id: "evt-006",
        title: "Lunch with Client",
        description: "Discuss partnership.",
        location: "The Capital Grille",
        start: "2026-02-18T12:00:00",
        end: "2026-02-18T13:30:00",
        allDay: false,
        category: "work",
        color: "#10b981",
        isBookable: false,
        createdBy: { id: "u-1", name: "Alex Rivera" },
    },
    {
        id: "evt-007",
        title: "Sprint Planning",
        start: "2026-02-17T14:00:00",
        end: "2026-02-17T15:30:00",
        allDay: false,
        category: "work",
        color: "#10b981",
        isBookable: true,
        createdBy: { id: "u-2", name: "Jordan Lee" },
    },
    {
        id: "evt-008",
        title: "Yoga Class",
        start: "2026-02-21T07:00:00",
        end: "2026-02-21T08:00:00",
        allDay: false,
        category: "personal",
        color: "#6366f1",
        isBookable: false,
        createdBy: { id: "u-1", name: "Alex Rivera" },
    },
    {
        id: "evt-009",
        title: "1:1 with Manager",
        start: "2026-02-18T09:00:00",
        end: "2026-02-18T09:45:00",
        allDay: false,
        category: "work",
        color: "#10b981",
        isBookable: false,
        createdBy: { id: "u-4", name: "Taylor Kim" },
    },
    {
        id: "evt-010",
        title: "API Integration Review",
        description: "Review third-party API changes.",
        start: "2026-02-19T10:00:00",
        end: "2026-02-19T11:00:00",
        allDay: false,
        category: "urgent",
        color: "#f59e0b",
        isBookable: true,
        createdBy: { id: "u-2", name: "Jordan Lee" },
    },
    {
        id: "evt-011",
        title: "Team Lunch",
        description: "Monthly bonding.",
        location: "Noodle House",
        start: "2026-02-20T12:00:00",
        end: "2026-02-20T13:00:00",
        allDay: false,
        category: "personal",
        color: "#6366f1",
        isBookable: false,
        createdBy: { id: "u-1", name: "Alex Rivera" },
    },
];

export const DEFAULT_HOLIDAYS = ["2026-02-16", "2026-12-25", "2026-01-01", "2026-07-04"];
export const DEFAULT_WORK_HOURS: WorkHours = { start: 9, end: 17 };
